# This is a (working) minimalist sample VM definition

# Usage:
#  mulch vm create sample-vm-simple.toml

name = "simple"
hostname = "simple.localdomain"

seed = "debian_9"

# Will speed up creation for this test (no update/upgrade)
# (but install will not be up to date, don't do this in production!)
init_upgrade = false

disk_size = "20G"
ram_size = "1G"
cpu_count = 1

# Restore (if needed)
restore_backup = "testvm-backup-20180917-172346.qcow2"
backup_prefix_url = "https://raw.githubusercontent.com/Xfennec/mulch/master/scripts/restore/"
backup = [
    "app@wordpress.sh",
]
