# This is a (working) sample VM definition

# Usage:
#  mulch vm create sample-vm.toml

name = "testvm"
hostname = "testvm.localdomain"
timezone = "Europe/Paris" # default
app_user = "app" # default

seed = "debian_9"

# Will speed up creation for this test (no update/upgrade)
# (but install will not be up to date, don't do this in production!)
init_upgrade = false

disk_size = "20G"
ram_size = "2G"
cpu_count = 1

# Define system wide environment variables
env = [
    ['TEST1', 'foo'],
    ['TEST2', 'bar'],
]

[[prepare]]
script_url = "https://raw.githubusercontent.com/Xfennec/mulch/master/scripts/prepare/deb-comfort.sh"
as = "admin"

[[prepare]]
script_url = "https://raw.githubusercontent.com/Xfennec/mulch/master/scripts/prepare/test-warn.sh"
as = "admin"

[[prepare]]
script_url = "https://raw.githubusercontent.com/Xfennec/mulch/master/scripts/prepare/deb-lamp.sh"
as = "admin"

[[prepare]]
script_url = "https://raw.githubusercontent.com/Xfennec/mulch/master/scripts/prepare/deb-wordpress.sh"
as = "app"
