# This is a (working) sample VM definition

# Usage:
#  mulch vm create sample-vm.toml

name = "testvm"
hostname = "testvm.localdomain"

seed_image = "debian-9-openstack-amd64.qcow2"

# Will speed up creation for this test (no update/upgrade)
# (but install will not be up to date, don't do this in production!)
init_upgrade = false 

disk_size = "20G"
ram_size = "2G"
cpu_count = 1
